id = "bsl"
name = "BSL"
version = "0.0.1"
schema_version = 1
authors = [
  "Dmitrii Liubanevich <dlyubanevich@gmail.com>",
  "alkoleft"
]
description = "BSL language support for checking the local tree-sitter-bsl grammar in Zed"
repository = "https://github.com/alkoleft/tree-sitter-bsl"

[grammars.bsl]
repository = "file:///home/alko/develop/open-source/tree-sitter-bsl"
rev = "fb137a374f5de02ef2a7ba24126e15f41af1702c"
path = "grammars/bsl"

[grammars.sdbl]
repository = "file:///home/alko/develop/open-source/tree-sitter-bsl"
rev = "fb137a374f5de02ef2a7ba24126e15f41af1702c"
path = "grammars/sdbl"
