id = "bsl"
name = "BSL"
version = "0.0.1"
schema_version = 1
authors = [
  "Dmitrii Liubanevich <dlyubanevich@gmail.com>",
  "alkoleft"
]
description = "BSL language support for checking the local tree-sitter-bsl grammar in Zed"
repository = "https://github.com/alkoleft/tree-sitter-bsl"

[grammars.bsl]
repository = "file:///home/alko/develop/open-source/tree-sitter-bsl"
rev = "f9fdbfb7fd8a9b549d3b95ff2dac4b6dd8c534b9"
path = "grammars/bsl"
