id = "bsl"
name = "BSL"
version = "0.0.1"
schema_version = 1
authors = [
  "Dmitrii Liubanevich <dlyubanevich@gmail.com>",
  "alkoleft"
]
description = "BSL language support for checking the local tree-sitter-bsl grammar in Zed"
repository = "https://github.com/alkoleft/tree-sitter-bsl"

[grammars.bsl]
repository = "file:///home/alko/develop/open-source/tree-sitter-bsl"
rev = "51521215783571a99e885786bb6d7de9cc49c1fd"
path = "grammars/bsl"

[grammars.sdbl]
repository = "file:///home/alko/develop/open-source/tree-sitter-bsl"
rev = "51521215783571a99e885786bb6d7de9cc49c1fd"
path = "grammars/sdbl"

[grammars.sdbl_embedded]
repository = "file:///home/alko/develop/open-source/tree-sitter-bsl"
rev = "51521215783571a99e885786bb6d7de9cc49c1fd"
path = "editors/zed-bsl/grammars/sdbl-embedded"
